wild-oasis/App/booking/routes.py
from App.extension import Blueprint, render_template

booking = Blueprint("booking", __name__)


@booking.route("/bookings", methods=["GET", "POST"])
def index():
    return render_template("booking/index.html")

wild-oasis/App/dashboard/routes.py
from App.extension import Blueprint, render_template, login_required

dashboard = Blueprint("dashboard", __name__)

@dashboard.route("/dashboard", methods=["GET", "POST"])
@login_required
def index():
    return render_template("dashboard/index.html")

wild-oasis/App/settings/routes.py
from App.extension import Blueprint, render_template

settings = Blueprint("settings", __name__)


@settings.route("/settings", methods=["GET", "POST"])
def index():
    return render_template("settings/index.html")

wild-oasis/App/templates/layout/aside.html
<div class="mb-4">
  <img src="../static/images/logo-light.png" alt="" />
</div>
<nav class="mt-6">
  <ul class="ml-3 space-y-6">
    <li
      class="hover:text-stone-400 text-lg transition-all hover:ease-linear hover:delay-100 hover:translate-x-2 hover:scale-110"
    >
      <a
        href="{{ url_for('dashboard.index') }}"
        class="flex items-center gap-3 hover:text-purple-600"
      >
        <img
          src="../static/images/home.svg"
          alt=""
          class="w-5 h-5 hover:bg-purple-600"
        />
        <span>Home</span>
      </a>
    </li>
    <li
      class="hover:text-stone-400 text-lg transition-all hover:ease-linear hover:delay-100 hover:translate-x-2 hover:scale-110"
    >
      <a
        href="{{ url_for('booking.index') }}"
        class="flex items-center gap-3 hover:text-purple-600"
      >
        <img
          src="../static/images/booking.svg"
          alt=""
          class="w-5 h-5 hover:bg-purple-600"
        />
        <span>Bookings</span>
      </a>
    </li>
    <li
      class="hover:text-stone-400 text-lg transition-all hover:ease-linear hover:delay-100 hover:translate-x-2 hover:scale-110"
    >
      <a
        href="{{ url_for('cabin.index') }}"
        class="flex items-center gap-3 hover:text-purple-600"
      >
        <img
          src="../static/images/cabin.svg"
          alt=""
          class="w-5 h-5 hover:bg-purple-600"
        />
        <span>Cabins</span>
      </a>
    </li>
    <li
      class="hover:text-stone-400 text-lg transition-all hover:ease-linear hover:delay-100 hover:translate-x-2 hover:scale-110"
    >
      <a
        href="{{ url_for('users.index') }}"
        class="flex items-center gap-3 hover:text-purple-600"
      >
        <img
          src="../static/images/users.svg"
          alt=""
          class="w-5 h-5 hover:bg-purple-600"
        />
        <span>Users</span>
      </a>
    </li>
    <li
      class="hover:text-stone-400 text-lg transition-all hover:ease-linear hover:delay-100 hover:translate-x-2 hover:scale-110"
    >
      <a
        href="{{ url_for('settings.index') }}"
        class="flex items-center gap-3 hover:text-purple-600"
      >
        <img
          src="../static/images/settings.svg"
          alt=""
          class="w-5 h-5 hover:bg-purple-600"
        />
        <span>Settings</span>
      </a>
    </li>
  </ul>
</nav>

wild-oasis/App/templates/layout/header.html
<div>
  <div>
    <img
      id="avatarButton"
      type="button"
      data-dropdown-toggle="userDropdown"
      data-dropdown-placement="bottom-start"
      class="w-10 h-10 rounded-full cursor-pointer"
      src="{{ url_for('static', filename='images/default.jpg') }}"
      alt="User dropdown"
    />

    <!-- Dropdown menu -->
    <div
      id="userDropdown"
      class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
    >
      <div class="px-4 py-3 text-sm text-gray-900 dark:text-white">
        <div>{{ current_user.fname }} {{ current_user.lname }}</div>
        <div class="font-medium truncate">{{ current_user.email }}</div>
      </div>
      <ul
        class="py-2 text-sm text-gray-700 dark:text-gray-200"
        aria-labelledby="avatarButton"
      >
        <li>
          <a
            href="#"
            class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >Profile</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >Settings</a
          >
        </li>
      </ul>
      <div class="py-1">
        <a
          href="{{ url_for('auth.logout') }}"
          class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
          >Log out</a
        >
      </div>
    </div>
  </div>
</div>

wild-oasis/App/templates/layout/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='dist/css/output.css')}}"
    />
    {{ toastr.include_jquery() }} {{ toastr.include_toastr_css() }} {{
    toastr.message() }}
    <script
      src="{{ url_for('static', filename='src/jquery-3.7.1.min.js') }}"
      defer
    ></script>
    <script src="{{ url_for('static', filename='src/script.js') }}"></script>
  </head>
  <body>
    <div
      class="grid grid-cols-[18rem_auto] grid-rows-[5rem_1fr] h-dvh bg-slate-50"
    >
      {% block header %}
      <header
        class="col-start-2 col-end-3 bg-slate-50 border-b-2 flex items-center justify-end px-3"
      >
        {% include './layout/header.html' %}
      </header>

      {% block message %} {% endblock %} {% endblock %} {% block aside %}
      <aside class="col-start-1 col-end-2 bg-slate-50 px-3 border-r-2">
        {% include './layout/aside.html' %}
      </aside>
      {% endblock %}

      <main class="col-start-2 col-end-3">
        {% block content %}
        <p>Content Area</p>
        {% endblock %}
      </main>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

    {{ toastr.include_toastr_js() }}
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
  </body>
</html>