flaskBlog/App/models/auth.py
from sqlalchemy import Column, String, Integer
from sqlalchemy.orm import relationship
from datetime import datetime
from flask_login import UserMixin
from App.extensions import db, login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    """Defines a User model"""
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False)
    email = Column(String(120), unique=True, nullable=False)
    password = Column(String(250), nullable=False)
    image_path = Column(String(120), nullable=True, default='default.png')
    created_at = Column(String, nullable=True, default=datetime.utcnow)
    posts = relationship('Post', backref="author", lazy=True)

    def __init__(self, username, email, password):
        self.id = self.id
        self.username = username
        self.email = email
        self.password = password

    def insert(self):
        """Insert a new user"""
        db.session.add(self)
        db.session.commit()

    def update(self):
        """A function that updates the user"""
        db.session.commit()

    def delete(self):
        """A function that deletes a user"""
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"User({self.username}, {self.email}, {self.created_at})"

flaskBlog/App/models/posts.py
from sqlalchemy import Column, String, Text, ForeignKey, Integer
from datetime import datetime
from flask_login import UserMixin
from App.extensions import db

class Post(db.Model, UserMixin):
    """A class that defines Post schema"""
    __tablename__ = 'posts'
    id = Column(Integer, primary_key=True)
    title = Column(String(60), nullable=False)
    description = Column(Text, nullable=False)
    post_date = Column(String, nullable=True, default=datetime.utcnow)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)

    def __init__(self, title, description, user_id):
        self.id = self.id
        self.title = title
        self.description = description
        self.user_id = user_id

    def insert(self):
        """A function that insert a new post"""
        db.session.add(self)
        db.session.commit()

    def update(self):
        """A function that update a given post"""
        db.session.commit()

    def delete(self):
        """A function that deletes a post"""
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Post({self.title}, {self.description}, {self.post_date}, {self.user_id})"

flaskBlog/App/main/forms.py
from flask_wtf import Form
from wtforms import StringField, EmailField, FileField, PasswordField, TextAreaField, SubmitField, validators, ValidationError

flaskBlog/App/posts/forms.py
from flask_wtf import Form
from wtforms import StringField, EmailField, FileField, PasswordField, TextAreaField, SubmitField, validators, ValidationError
from flask_login import current_user
from App.models.auth import User

class PostForm(Form):
    title = StringField("Title", [validators.DataRequired(
        message="Title is required")])
    description = TextAreaField(
        "Description", [validators.DataRequired(message="Description is required")])
    post = SubmitField("Post")


class UpdatePostForm(Form):
    title = StringField("Title", [validators.DataRequired(
        message="Title is required")])
    description = TextAreaField(
        "Description", [validators.DataRequired(message="Description is required")])
    update = SubmitField("Update")

class UpdateForm(Form):
    username = StringField("Username", [validators.InputRequired(
        message="Username is required"), validators.Length(min=2, max=25, message="Username must be above 2 & not more than 25")])
    email = EmailField(
        "Email", [validators.InputRequired(message="Email field cannot be empty")])
    picture = FileField('Select file', name='file')
    update = SubmitField("Update")

    def validate_username(self, username):
        """Function that validate existance of username"""
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    "Username already taken")

    def validate_email(self, email):
        """Function that validates the existance of email"""
        if email.data != current_user.email:
            email = User.query.filter_by(email=email.data).first()
            if email:
                raise ValidationError("Email already in use")

flaskBlog/App/__init__.py
import config
import secrets
from PIL import Image
from flask import Flask

from App.models.auth import login_manager
from App.extensions import db, bcrypt, csrf, migrate, cors


login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'info'


def create_app(config=config.DevelopmentConfig):

    app = Flask(__name__)
    app.config.from_object(config)
    db.init_app(app)
    bcrypt.init_app(app)
    csrf.init_app(app)
    migrate.init_app(app)
    cors.init_app(app)
    login_manager.init_app(app)

    from App.auth.routes import auth_bp
    app.register_blueprint(auth_bp)

    from App.main.routes import main_bp
    app.register_blueprint(main_bp)

    from App.posts.routes import posts_bp 
    app.register_blueprint(posts_bp)

    return app

flaskBlog/App/main/routes.py
from flask import Blueprint, request, render_template
from App.models.auth import User
from App.models.posts import Post


main_bp = Blueprint("main", __name__)


@main_bp.route('/')
@main_bp.route('/index') 
def index():
    # all_post = Post.query.join(User, Post.user_id == User.id).all()
    page = request.args.get('page', 1, type=int)

    all_post = Post.query.join(User).\
        with_entities(Post.id, Post.title, Post.description, Post.post_date, User.username).\
        order_by(Post.post_date.desc()).paginate(page=page, per_page=2)
    return render_template('main_templates/home.html', title='Home', posts=all_post)


@main_bp.route('/about')
def about():
    return render_template('main_templates/about.html', title='About Us')

flaskBlog/App/posts/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, abort
from flask_login import login_required, current_user
from App.posts.forms import PostForm, UpdatePostForm
from App.models.posts import Post
from App.models.auth import User 

posts_bp = Blueprint('posts', __name__, static_folder='static')


@posts_bp.route('/create_post', methods=['GET', 'POST'])
@login_required
def create_post():
    """This route create new post"""
    form = PostForm(request.form)
    if request.method == 'POST' and form.validate():
        post = Post(title=form.title.data,
                    description=form.description.data, user_id=current_user.id)
        post.insert()
        flash("New post successfully added", "success")
        return redirect(url_for('main.index'))
    elif request.method == 'GET':
        ...
    return render_template('posts_templates/create_post.html', title='New Post', form=form)


@posts_bp.route('/show_post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    form = UpdatePostForm(request.form)
    if request.method == 'GET':
        post = Post.query.filter_by(id=post_id).join(User).first()
    elif request.method == 'POST' and form.validate():
        post = Post.query.filter_by(id=post_id).first()
        post.title = form.title.data
        post.description = form['description'].data
        post.update()
        flash("Post successfully updated", "success")
        return redirect(url_for('main.index'))
    return render_template('posts_templates/show_post.html', title='Show Post', post=post, form=form)


@posts_bp.route('/post/delete/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    if request.method == 'POST':
        post = Post.query.filter_by(id=post_id).first()
        if post:
            post.delete()
            flash("Post successfully deleted", "success")
            return redirect(url_for('main.index'))
        else:
            abort(404)

flaskBlog/App/templates/layouts.html
{% include './partials/head.html' %} {% include './partials/nav.html' %}

<main class="container">
  <div class="row">
    <div class="col-md-8">
      {% with messages = get_flashed_messages(with_categories = true)%} {% if
      messages %} {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %} {% endif %} {% endwith %} {%block content %} {% endblock
      content %}
    </div>
    <div class="col-md-4">
      <div class="list-group">
        <a
          href="#"
          class="list-group-item list-group-item-action active"
          aria-current="true"
        >
          The current link item
        </a>
        <a href="#" class="list-group-item list-group-item-action"
          >A second link item</a
        >
        <a href="#" class="list-group-item list-group-item-action"
          >A third link item</a
        >
        <a href="#" class="list-group-item list-group-item-action"
          >A fourth link item</a
        >
        <a class="list-group-item list-group-item-action disabled"
          >A disabled link item</a
        >
      </div>
    </div>
  </div>
</main>
{% include './partials/footer.html' %}

flaskBlog/App/templates/main.html
{% extends 'layouts.html' %} {% block content %}
<main>
  <div class="container">
    <div class="row">
      <div class="col-7">{% block mainleft%} {% endblock mainleft %}</div>
      <div class="col-5">{% block mainright %} {% endblock mainright %}</div>
    </div>
  </div>
</main>

{% endblock content %}

flaskBlog/App/templates/main_templates/about.html
{% extends 'layouts.html' %} {% block content %}
<main>
  <!-- <div class="container">
            <div class="row">
            <div class="col-8">col-8</div>
            <div class="col-4">col-4</div>
            </div>
        </div> -->

  <h2>This is the about page</h2>
</main>

{% endblock content %}

flaskBlog/App/templates/main_templates/home.html
{% extends 'layouts.html' %} {% block content %}
<!-- <main>
  <div class="container">
    <div class="row">
      <div class="col-8"> -->
{% if posts %} {% for post in posts.items %}
<div class="card w-75 mb-3">
  <div class="card-body">
    <div class="d-flex justify-content-start align-items-center">
      <h3 class="card-title">{{ post.title }}</h3>
      <span class="text-muted text-md mx-1">By {{ post.username }}</span>
      <span class="text-muted text-sm mx-1">{{ post.post_date }}</span>
    </div>
    <p class="card-text">{{post.description}}</p>
    <a
      href="{{ url_for('posts.show_post', post_id=post.id) }}"
      class="btn btn-info"
      >Read more</a
    >
  </div>
</div>
{% endfor %} {% else %}
<p class="display-2">No post available</p>
{% endif %}

<div class="pagination">
  {% if posts.has_prev %}
  <a href="" class="page-item" aria-label="Previous">
    <span class="page-link"> &laquo; </span>
  </a>
  {% endif %} {% for number in posts.iter_pages() %} {% if posts.page != number
  %}
  <span class="page-item">
    <a href="{{ url_for('main.index', page=number) }}" class="page-link"
      >{{ number }}</a
    >
  </span>
  {% else %}
  <span class="page-item"><a href="" class="page-link">{{ number }}</a></span>
  {% endif %} {%endfor %} {% if posts.has_next %}
  <span class="page-item">
    <a href="{{ url_for('main.index', page=posts.next_num) }}" class="page-link"
      >&raquo;</a
    >
  </span>
  {% endif %}
</div>

{% endblock content %}

flaskBlog/App/templates/partials/footer.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='js/index.js') }}"></script>
</body>
</html>

flaskBlog/App/templates/partials/head.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    {% if title %}
    <title>UFAZ blog - {{ title }}</title>
    {% else %}
    <title>UFAZ blog</title>
    {% endif %}
  </head>
  <body></body>
</html>

flaskBlog/App/templates/partials/nav.html
<nav class="container-fluid text-bg-info p-3 mb-5 text-white">
  <div class="container d-flex justify-content-between">
    <a class="navbar-brand fs-3" href="{{ url_for('main.index') }}"
      >Flask Blog</a
    >
    <div class="">
      <ul class="d-flex flex-row justify-content-evenly fs-4 list-unstyled">
        <li class="px-3">
          <a
            href="{{ url_for('main.index') }}"
            class="text-decoration-none text-white"
            >Home</a
          >
        </li>
        <li class="px-3">
          <a href="" class="text-decoration-none text-white">Blogs</a>
        </li>
        <li class="px-3">
          <a href="" class="text-decoration-none text-white">Contact</a>
        </li>
      </ul>
    </div>
    <div class="">
      <ul
        class="d-flex flex-row justify-content-between fs-4 list-unstyled ps-2"
      >
        {% if current_user.is_authenticated %}
        <li class="px-3">
          <a
            href="{{ url_for('posts.create_post') }}"
            class="text-decoration-none text-white"
            >New Post</a
          >
        </li>
        <li class="px-3">
          <a
            href="{{ url_for('auth.dashboard') }}"
            class="text-decoration-none text-white"
            >Dashboard</a
          >
        </li>
        <li class="px-3">
          <a
            href="{{ url_for('auth.logout') }}"
            class="text-decoration-none text-white"
            >logout</a
          >
        </li>
        {% else %}
        <li class="px-3">
          <a
            href="{{ url_for('auth.login') }}"
            class="text-decoration-none text-white"
            >Login</a
          >
        </li>
        <li class="px-3">
          <a
            href="{{ url_for('auth.register') }}"
            class="text-decoration-none text-white"
            >Sign Up</a
          >
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

flaskBlog/App/templates/posts_templates/create_post.html
{% extends 'layouts.html' %} {% block content %}

<form action="" method="POST">
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Create Post</legend>
    <div class="form-group mb-3">
      {{ form.title.label(class="form-control-label") }} {% if form.title.errors
      %} {{ form.title(class="form-control form-control-lg") }} {% for error in
      form.title.errors %}
      <p class="text-danger text-sm">{{ error }}</p>
      {% endfor %} {% else %} {{ form.title(class="form-control
      form-control-lg") }} {% endif %}
    </div>
    <div class="form-group mb-3">
      {{ form.description.label(class="form-control-label") }} {% if
      form.description.errors %} {{ form.description(class="form-control
      form-control-lg") }} {% for error in form.description.errors %}
      <p class="text-danger text-sm">{{ error }}</p>
      {% endfor %} {% else %} {{ form.description(class="form-control
      form-control-lg") }} {% endif %}
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="form-group mb-3">
      {{ form.post(class="btn btn-lg btn-outline-info") }}
    </div>
  </fieldset>
</form>

{% endblock content %}

flaskBlog/App/templates/posts_templates/show_post.html
{% extends 'layouts.html' %} {% block content %} {% if post %}
<div class="card w-75 mb-3">
  <div class="card-body">
    <div class="d-flex flex-column" id="post-container">
      <div class="d-flex justify-content-between">
        <h3 class="card-title">{{ post.title }}</h3>
        {% if current_user.is_authenticated %}
        <div class="d-flex justify-content-around">
          <a
            href="#"
            class="btn btn-sm btn-secondary mx-3"
            data-bs-toggle="modal"
            data-bs-target="#editModal"
            >Edit</a
          >
          <a
            href="#"
            class="btn btn-sm btn-danger"
            data-bs-toggle="modal"
            data-bs-target="#deleteModal"
            >Delete</a
          >
        </div>
        {% endif %}
      </div>
      <span class="text-muted text-md mx-1">By {{ post.author.username }}</span>
      <span class="text-muted text-sm mx-1 mb-3">{{ post.post_date }}</span>
    </div>
    <p class="card-text">{{ post.description }}</p>
  </div>
</div>
{% else %}
<p class="display-2 text-muted">Page Not found</p>
<a href="{{ url_for('main.index') }}" class="text-info text-xl">Back</a>
{% endif %}

<!-- Modal form for editing Post -->
<div
  class="modal fade"
  id="editModal"
  tabindex="-1"
  aria-labelledby="editModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editModalLabel">Update Post</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="" method="POST">
          <fieldset class="form-group">
            <div class="form-group mb-3">
              {{ form.title.label(class="form-control-label") }} {% if
              form.title.errors %} {{ form.title(class="form-control
              form-control-lg") }} {% for error in form.title.errors %}
              <p class="text-danger text-sm">{{ error }}</p>
              {% endfor %} {% else %} {{ form.title(class="form-control
              form-control-lg", value=post.title) }} {% endif %}
            </div>
            <div class="form-group mb-3">
              {{ form.description.label(class="form-control-label") }} {% if
              form.description.errors %} {{ form.description(class="form-control
              form-control-lg") }} {% for error in form.description.errors %}
              <p class="text-danger text-sm">{{ error }}</p>
              {% endfor %} {% else %}
              <textarea
                name="description"
                class="form-control form-control-lg"
                id=""
                cols="30"
                rows="5"
              >
              {{ post.description }}</textarea
              >
              {% endif %}
            </div>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            {{ form.update(class="btn btn-lg btn-outline-info") }}
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Delete Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">Are you sure you want to delete?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          No
        </button>

        <form
          action="{{ url_for('posts.delete_post', post_id=post.id) }}"
          method="POST"
        >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <input type="submit" class="btn btn-danger" value="Yes" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}